version: '3.7'

services:
  app:
    build: .
    restart: on-failure:3
    command: npm run dev
    depends_on:
      - database
    volumes:
      - ./:/usr/app
    ports:
      - "3000:3000"
    networks:
      - notification_service

  database:
    image: mongo:latest
    restart: on-failure:3
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DATABASE_USER
      MONGO_INITDB_ROOT_PASSWORD: $DATABASE_PASSWORD
      MONGO_INITDB_DATABASE: $DATABASE_NAME
    volumes: 
      - ./mongodb:/data/db
    logging:
      driver: none
    networks:
      - notification_service

  smtp:
    platform: linux/x86_64
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - notification_service

volumes:
  mongodb:
    driver: local

networks:
  notification_service:
    driver: bridge 
