version: '3.7'

services:
  app:
    build: .
    restart: on-failure:3
    command: npm run dev
    depends_on:
      - database
    volumes:
      - ./:/usr/app
    ports:
      - 3000:3000
    networks:
      - notification-service

  database:
    image: mongo
    restart: on-failure:3
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DATABASE_USER
      MONGO_INITDB_ROOT_PASSWORD: $DATABASE_PASSWORD
      MONGO_INITDB_DATABASE: $DATABASE_NAME
    volumes: 
      - ./mongodb:/data/db
    logging:
      driver: none
    networks:
      - notification-service
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DATABASE_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DATABASE_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017/
    logging:
      driver: none
    networks:
      - notification-service
      
networks:
  notification-service:
    driver: bridge

volumes:
  mongodb:
    driver: local

  
