version: '3.7'

services:
  app:
    build: .
    restart: on-failure:3
    command: npm run dev
    depends_on:
      - database
    volumes:
      - ./:/usr/app
    ports:
      - "3000:3000"

  # database:
  #   image: mongo:latest
  #   restart: on-failure:3
  #   ports:
  #    - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: $DATABASE_USER
  #     MONGO_INITDB_ROOT_PASSWORD: $DATABASE_PASSWORD
  #     MONGO_INITDB_DATABASE: $DATABASE_NAME
  #   volumes: 
  #     - ./mongodb:/data/db
  #   logging:
  #     driver: none

volumes:
  mongodb:
    driver: local

  
